### ISSUE TITLE
Web font Loading delay

### ISSUE THREAD

**Issue by AdnanAfsari** [Codivox/codivox.com#65]
**My Findings while visiting codivox.com**

- Font takes few seconds extra to load after the site load.

- There is a visible transition of font after loading which is not a good UX and ca be improved.

**My Proposals**

- We can use [gatsby-plugin-prefetch-google-fonts](https://www.gatsbyjs.com/plugins/gatsby-plugin-prefetch-google-fonts/#gatsby-plugin-prefetch-google-fonts) instead of gatsby-plugin-web-font-loader plugin.

- We can Enable Offline Mode for Your Gatsby Site proving Cache functionality to improve our site performance dramatically. Reference [Link](https://www.freecodecamp.org/news/how-to-enable-offline-mode-for-gatsby-site/)

**Comment by inhaq** [comment]
Let's start with adding a plugin for fonts and then add offline mode.

**Comment by AdnanAfsari** [comment]
On it
